### ISSUE TITLE
Support for imported functions 

### ISSUE THREAD

**Issue by zant** [101arrowz/isoworker#1]
Hey @101arrowz starting a discussion here just to not clutter [#77](https://github.com/alewin/useWorker/issues/77) that much.

Just tried `isoworker` from npm and it works like a charm, thanks again! 

Now there's a minor thing that came out after a bit of testing and it’s that imported functions are not working due to bundling. 

For example, if I do:

```js
import { add } from "./utils";

const [thingyWorker] = useWorker(thingyFn, {
    localDependencies: () => [thingy, add],
});
```
```js
// On useWorker side we're doing something like this
const createWorkerBlobUrl = (
  localDeps: () => unknown[], // This is exactly what is passed to the hook
) => {
  const context = isoworker.createContext(localDeps)
```

What `isoworker` gets is:

```
() => [thingy, _utils__WEBPACK_IMPORTED_MODULE_3__["add"]]
```

As you can see it doesn't get the correct function's name. A possible workaround that could help is having a different way to interface with `createContext`. For example, passing functions in an object would allow us to have both correct naming and function declaration even on imported functions.

```js
const context = isoworker.createContext({ thingy, add })
```

 What do you think?

**Comment by 101arrowz** [comment]
If you check the minified code, it's quite likely `thingy` calls `_utils__WEBPACK_IMPORTED_MODULE_3__.add`, not `add`. The reason I did it this way is that minifiers rename variables and functions, which makes an object mapping fail in production; what you've observed is an oversight by me. I need access to the original names of the variables, and functions are the only way I found to do this.

Imported things failing can be worked around by assigning to a local variable. That, or I could try to parse the object accessor and create a wrapper object whenever I see that a key of an object is being accessed.

**Comment by zant** [comment]
You're right, and even if `isoworker` gets the correct function name, whatever function that calls it will be calling `_utils__WEBPACK_IMPORTED_MODULE_3__.add` because of minification. So I think the proper workaround will be just to re-declare locally. 

Feels just a bit odd for our use case in `useWorker` but I thing we will find a way to make it friendlier.

**Comment by 101arrowz** [comment]
You may not need to worry about it; I found a solution that could possibly help. It parses property accessors and creates objects automatically for them and all children. I'll push an update when it's finished, but in theory you won't even need to redeclare a local variable.

**Comment by zant** [comment]
Sounds great @101arrowz! I'll keep an eye on the repo for updates 👌

**Comment by 101arrowz** [comment]
@zant I've updated the NPM version with the necessary changes, and I think the nested property access works now. Could you try it out?

**Comment by zant** [comment]
The snippet above is now working perfectly! Really clever solution 👌 thanks for the amazing effort @101arrowz!
