### ISSUE TITLE
default export

### ISSUE THREAD

**Issue by jer-sen** [101arrowz/isoworker#2]
Could you add a default export so that isoworker as EcmaScript module can be imported (so used) from a non EcmaScript module ?

**Comment by 101arrowz** [comment]
This is already done, you should be able to use the CommonJS export with a simple `require` call, as in:

```js
const isoworker = require('isoworker');
isoworker.workerize(...);

// Alternatively,
const { workerize } = require('isoworker');
workerize(...);
```

Is this not working for you, or are you looking for some other kind of export?

**Comment by jer-sen** [comment]
Your code is ok and I think everything is fine with CommonJS.

The issue is with EcmaScript modules. In a browser or with a bundler, from a non module script, you can only import the default export of a module. The EcmaScript module version in your build should expose everything in an object as a default export.

**Comment by yuval-a** [comment]
> This is already done, you should be able to use the CommonJS export with a simple `require` call, as in:
> 
> ```js
> const isoworker = require('isoworker');
> isoworker.workerize(...);
> 
> // Alternatively,
> const { workerize } = require('isoworker');
> workerize(...);
> ```
> 
> Is this not working for you, or are you looking for some other kind of export?

When trying to ues `require` I get this error message:
`Must use import to load ES Module`
When trying to use the `import` alternatives I always get:
`Cannot use import statement outside a module`

**Comment by 101arrowz** [comment]
[package.json](https://www.github.com/101arrowz/isoworker/tree/master/package.json) has a `main` and a `module`. This means both CommonJS and ESM work in bundlers and Node.js. What environment are you in where this is failing?
